// map country names returned from expo-location reversegeocodeasync to us state dept advisory IDs
// da source: cadataapi.state.gov/api/TravelAdvisories
const countryToUSId = {
  "Haiti": "HA",
  "Hungary": "HU",
  "Trinidad and Tobago": "TD",
  "Barbados": "BB",
  "Bermuda": "BD",
  "Oman": "OM",
  "Luxembourg": "LU",
  "Nigeria": "NI",
  "Costa Rica": "CS",
  "Latvia": "LG",
  "Ethiopia": "ET",
  "Estonia": "EN",
  "Nepal": "NP",
  "Gabon": "GB",
  "Ireland": "EI",
  "Venezuela": "VE",
  "Saudi Arabia": "SA",
  "Finland": "FI",
  "Guatemala": "GT",
  "Azerbaijan": "AJ",
  "Belize": "BH",
  "Togo": "TO",
  "Singapore": "SN",
  "Kuwait": "KU",
  "Turkey": "TU",
  "Cyprus": "CY",
  "Pakistan": "PK",
  "United Arab Emirates": "AE",
  "Qatar": "QA",
  "Jordan": "JO",
  "Iraq": "IZ",
  "Bahrain": "BA",
  "Guinea": "GV",
  "Malawi": "MI",
  "Lebanon": "LE",
  "Malaysia": "MY",
  "Afghanistan": "AF",
  "Cote d'Ivoire": "IV",
  "Ivory Coast": "IV",
  "Slovakia": "LO",
  "Kyrgyzstan": "KG",
  "The Kyrgyz Republic": "KG",
  "Uzbekistan": "UZ",
  "Bangladesh": "BG",
  "Jamaica": "JM",
  "The Gambia": "GA",
  "Gambia": "GA",
  "Comoros": "CN",
  "Mali": "ML",
  "Benin": "BN",
  "Grenada": "GJ",
  "Belarus": "BO",
  "Russia": "RS",
  "Yemen": "YM",
  "Cabo Verde": "CV",
  "Cape Verde": "CV",
  "Syria": "SY",
  "Guinea-Bissau": "GW",
  "Liberia": "LI",
  "Seychelles": "SE",
  "Mauritius": "MP",
  "Uganda": "UG",
  "Iran": "IR",
  "Madagascar": "MA",
  "Senegal": "SG",
  "Taiwan": "TW",
  "South Sudan": "OD",
  "Central African Republic": "CT",
  "Tanzania": "TZ",
  "Niger": "NG",
  "Greece": "GR",
  "Bhutan": "BT",
  "Sudan": "SU",
  "Ecuador": "EC",
  "Romania": "RO",
  "Bulgaria": "BU",
  "Croatia": "HR",
  "Sri Lanka": "CE",
  "Sao Tome and Principe": "TP",
  "Maldives": "MV",
  "Equatorial Guinea": "EK",
  "Antarctica": "AY",
  "Sierra Leone": "SL",
  "Armenia": "AM",
  "Democratic Republic of the Congo": "CG",
  "DR Congo": "CG",
  "Mexico": "MX",
  "Cambodia": "CB",
  "Thailand": "TH",
  "Rwanda": "RW",
  "Libya": "LY",
  "Egypt": "EG",
  "Mauritania": "MR",
  "Marshall Islands": "RM",
  "Mozambique": "MZ",
  "India": "IN",
  "Dominican Republic": "DR",
  "Canada": "CA",
  "Poland": "PL",
  "Australia": "AS",
  "Brazil": "BR",
  "Malta": "MT",
  "South Korea": "KS",
  "Korea, Republic of": "KS",
  "France": "FR",
  "South Africa": "SF",
  "Italy": "IT",
  "Belgium": "BE",
  "Liechtenstein": "LS",
  "Vanuatu": "NH",
  "Switzerland": "SR",
  "Tajikistan": "TI",
  "Peru": "PE",
  "Japan": "JA",
  "Somalia": "SO",
  "Germany": "GM",
  "Myanmar": "BM",
  "Burma": "BM",
  "Spain": "SP",
  "Guyana": "GY",
  "Philippines": "RP",
  "United Kingdom": "UK",
  "Uruguay": "UY",
  "Cuba": "CU",
  "Paraguay": "PA",
  "Indonesia": "ID",
  "North Korea": "KN",
  "Papua New Guinea": "PP",
  "Burundi": "BY",
  "Solomon Islands": "BP",
  "Czechia": "EZ",
  "Czech Republic": "EZ",
  "Morocco": "MO",
  "Colombia": "CO",
  "Burkina Faso": "UV",
  "Serbia": "RI",
  "Ghana": "GH",
  "El Salvador": "ES",
  "The Bahamas": "BF",
  "Bahamas": "BF",
  "Andorra": "AN",
  "Timor-Leste": "TT",
  "East Timor": "TT",
  "Brunei": "BX",
  "Chad": "CD",
  "Kenya": "KE",
  "Georgia": "GG",
  "Samoa": "WS",
  "Djibouti": "DJ",
  "Turks and Caicos Islands": "TK",
  "Portugal": "PO",
  "Turkmenistan": "TX",
  "Norway": "NO",
  "Mongolia": "MG",
  "Micronesia": "FM",
  "Federated States of Micronesia": "FM",
  "Chile": "CI",
  "North Macedonia": "MK",
  "Macedonia": "MK",
  "New Zealand": "NZ",
  "Albania": "AL",
  "Namibia": "WA",
  "Cameroon": "CM",
  "Vietnam": "VM",
  "Viet Nam": "VM",
  "Suriname": "NS",
  "Nicaragua": "NU",
  "Bosnia and Herzegovina": "BK",
  "Bosnia": "BK",
  "Honduras": "HO",
  "Saint Vincent and the Grenadines": "VC",
  "Tuvalu": "TV",
  "Kiribati": "KR",
  "Tonga": "TN",
  "Nauru": "NR",
  "Fiji": "FJ",
  "Kosovo": "KV",
  "Moldova": "MD",
  "China": "CH",
  "Hong Kong": "HK",
  "Macau": "MC",
  "Macao": "MC",
  "Montenegro": "MJ",
  "Laos": "LA",
  "Ukraine": "UP",
  "Greenland": "GL",
  "Tunisia": "TS",
  "Republic of the Congo": "CF",
  "Congo": "CF",
  "Algeria": "AG",
  "Angola": "AO",
  "Panama": "PM",
  "Argentina": "AR",
  "Lesotho": "LT",
  "Denmark": "DA",
  "Cayman Islands": "CJ",
  "Austria": "AU",
  "Iceland": "IC",
  "British Virgin Islands": "VI",
  "Dominica": "DO",
  "Anguilla": "AV",
  "Saint Kitts and Nevis": "SC",
  "Saint Lucia": "ST",
  "Antigua and Barbuda": "AC",
  "Montserrat": "MH",
  "Curaçao": "UC",
  "Curacao": "UC",
  "Aruba": "AA",
  "Sint Maarten": "NN",
  "Netherlands": "NL",
  "Lithuania": "LH",
  "Palau": "PS",
  "Kazakhstan": "KZ",
  "Slovenia": "SI",
  "Sweden": "SW",
  "Eswatini": "WZ",
  "Swaziland": "WZ",
  "Bolivia": "BL",
  "Botswana": "BC",
  "Zambia": "ZA",
  "Eritrea": "ER",
  "Zimbabwe": "ZI",
};

export function getUSAdvisoryId(countryName) {
  if (!countryName) return null;
  return countryToUSId[countryName] || null;
}