import { StyleSheet } from "react-native";
// import { LinearGradient } from "expo-linear-gradient"; 

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  contentContainer: {
    paddingTop: 16,
    paddingBottom: 28,
  },
  weatherBanner: {
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  weatherDay: {
    backgroundColor: "#dbeafe",
  },
  weatherNight: {
    backgroundColor: "#112d5b",
  },
  weatherEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "#475569",
  },
  weatherTemp: {
    marginTop: 4,
    fontSize: 30,
    fontWeight: "800",
    color: "#0f172a",
  },
  weatherCondition: {
    marginTop: 4,
    fontSize: 14,
    color: "#334155",
  },
  weatherAside: {
    alignItems: "flex-end",
  },
  weatherTextNight: {
    color: "#ffffff",
  },
  weatherRangeLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  weatherRange: {
    marginTop: 6,
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  mapSection: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 14,
    overflow: "hidden",
    height: 420,
  },
  loadingText: {
    marginHorizontal: 16,
    marginTop: 8,
    color: "#475569",
    fontSize: 14,
  },
  alertBox: {
    backgroundColor: "#fee2e2",
    padding: 12,
    marginTop: 10,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  alertTitle: {
    color: "#991b1b",
    fontWeight: "700",
  },
  alertHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  closeButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fecaca",
  },
  closeButtonText: {
    fontSize: 14,
    color: "#991b1b",
    fontWeight: "700",
  },
  alertDescription: {
    color: "#7f1d1d",
  },
  buttonWrapper: {
    marginTop: 14,
    marginHorizontal: 16,
  },
  refreshButton: {
    backgroundColor: "#0f172a",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
  },
  refreshButtonPressed: {
    opacity: 0.85,
  },
  refreshButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginTop: 22,
    marginBottom: 14,
    marginHorizontal: 16,
    color: "#111827",
  },
  carouselContainer: {
    minHeight: 300,
  },
  cardWrapper: {
    paddingBottom: 18,
  },
  newsSectionHeader: {
    marginTop: 8,
    marginHorizontal: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  newsRefreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e2e8f0",
  },
  newsRefreshIcon: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
  },
  newsSection: {
    marginHorizontal: 16,
    marginBottom: 12,
  },
  newsCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  newsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  newsBadge: {
    fontSize: 12,
    fontWeight: "700",
    color: "#000000",
    backgroundColor: "#96a4e7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 25,
  },
  newsSeverity: {
    fontSize: 12,
    fontWeight: "700",
    color: "#b45309",
  },
  newsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 6,
  },
  newsDescription: {
    fontSize: 14,
    color: "#4b5563",
    lineHeight: 20,
  },
  newsMeta: {
    marginTop: 10,
    fontSize: 12,
    color: "#6b7280",
  },
  emptyNewsText: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 20,
  },
  weatherBannerPressed: {
    opacity: 0.92,
  },
  weatherTapHint: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
    justifyContent: "flex-end",
  },
  modalOverlay: {
    flex: 1,
  },

  // weather stuff
  weatherModalSheet: {
    maxHeight: "88%",
    backgroundColor: "#163b97",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 16,
    paddingHorizontal: 14,
    paddingBottom: 28,
  },
  weatherModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  weatherModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ffffff",
  },
  weatherModalCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  weatherModalCloseText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
  },
  weatherModalContent: {
    paddingBottom: 30,
  },
  weatherHeroCard: {
    backgroundColor: "rgba(8, 26, 79, 0.45)",
    borderRadius: 24,
    padding: 20,
    marginBottom: 14,
  },
  weatherHeroEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "rgba(255,255,255,0.7)",
  },
  weatherHeroTemp: {
    marginTop: 6,
    fontSize: 42,
    fontWeight: "800",
    color: "#ffffff",
  },
  weatherHeroCondition: {
    marginTop: 6,
    fontSize: 18,
    color: "rgba(255,255,255,0.9)",
  },
  weatherHeroRange: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: "700",
    color: "rgba(255,255,255,0.7)",
  },
  weatherLoadingBlock: {
    paddingVertical: 24,
    alignItems: "center",
  },
  weatherLoadingText: {
    marginTop: 10,
    fontSize: 14,
    color: "rgba(255,255,255,0.82)",
  },
  weatherMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  weatherMetricCard: {
    width: "48%",
    minHeight: 210,
    backgroundColor: "#204db6",
    borderRadius: 26,
    padding: 18,
    marginBottom: 12,
    justifyContent: "space-between",
    shadowColor: "#0b1f57",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  weatherMetricLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.82)",
  },
  weatherMetricDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 22,
    color: "rgba(255,255,255,0.92)",
  },
  weatherMetricValue: {
    marginTop: 14,
    fontSize: 32,
    fontWeight: "800",
    color: "#ffffff",
  },
  weatherMetricValueSmall: {
    marginTop: 14,
    fontSize: 20,
    fontWeight: "800",
    color: "#ffffff",
  },
  uvBarTrack: {
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  uvBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#facc15",
  },
  humidityBarTrack: {
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  humidityBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#7dd3fc",
  },
  weatherSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 12,
    marginTop: 8,
  },
  forecastList: {
    marginTop: 4,
  },
  forecastRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(8, 26, 79, 0.45)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  forecastDay: {
    fontSize: 15,
    fontWeight: "700",
    color: "#ffffff",
  },
  forecastCondition: {
    marginTop: 2,
    fontSize: 13,
    color: "rgba(255,255,255,0.7)",
  },
  forecastTemps: {
    fontSize: 15,
    fontWeight: "800",
    color: "#ffffff",
  },
  emptyForecastText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 14,
    lineHeight: 20,
  },
  weatherMetricDescription: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: "rgba(255,255,255,0.9)",
  },
  uvBarTrack: {
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  uvBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#facc15",
  },
  humidityBarTrack: {
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  humidityBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#7dd3fc",
  },
  sunCard: {
    height: 250,
    width: "100%",
    backgroundColor: "rgba(8, 26, 79, 0.45)",
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingBottom: 20,
    marginBottom: 16,
    overflow: "hidden",
  },
  sunCurveWrapper: {
    height: 145,
    justifyContent: "flex-end",
    alignItems: "center",
    position: "relative",
    paddingBottom: 80,
  },
  sunCurveGlow: {
    position: "absolute",
    top: 32,
    width: "70%",
    height: 95,
    borderTopLeftRadius: 200,
    borderTopRightRadius: 200,
    backgroundColor: "rgba(250, 204, 21, 0.31)",
  },
  sunCurveArc: {
    position: "absolute",
    top: 28,
    width: "70%",
    height: 99,
    borderTopLeftRadius: 180,
    borderTopRightRadius: 180,
    borderWidth: 6,
    borderBottomWidth: 0,
    borderColor: "#ffdb11",
    backgroundColor: "transparent",
  },
  sunHorizon: {
    position: "absolute",
    bottom: 18,
    width: "110%",
    height: 2,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  sunTimesRow: {
    marginTop: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  sunTimesRight: {
    alignItems: "flex-end",
  },
  sunTimeLabel: {
    fontSize: 14,
    color: "rgba(255,255,255,0.72)",
    marginBottom: 6,
  },
  sunTimeValue: {
    fontSize: 28,
    fontWeight: "800",
    color: "#ffffff",
  },
});

export default styles;