import { StyleSheet } from "react-native";
import { shared } from "./sharedStyles.js";

export const styles = StyleSheet.create({
  outerContainer: shared.container,
  container: shared.scrollContent,
  title: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 12,
  },
  empty: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 6,
    color: "#111827",
  },
  cardSubtitle: {
    fontSize: 14,
    color: "#444",
    marginBottom: 8,
  },
  location: {
    fontSize: 13,
    color: "#6b7280",
    marginBottom: 8,
  },
  cardRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 8,
  },
  cardImage: {
    width: 72,
    height: 72,
    borderRadius: 6,
    backgroundColor: "#e5e7eb",
  },
  cardActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  actionButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  undoButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: "#6b7280",
    alignSelf: "flex-start",
    marginTop: 4,
  },
  visitedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  visitedHeaderText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#10b981",
  },
  stickyFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 8,
  },
  generateButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#2563eb",
    borderRadius: 8,
    alignItems: "center",
  },
  generateButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  generateLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  generateHelper: {
    fontSize: 13,
    color: "#6b7280",
    marginTop: 8,
    textAlign: "center",
  },
  errorHint: {
    fontSize: 12,
    color: "#ef4444",
    textAlign: "center",
    marginBottom: 6,
  },
  itinerarySummary: {
    fontSize: 14,
    color: "#374151",
    marginBottom: 12,
    fontStyle: "italic",
  },
  aiWarningText: {
    fontSize: 12,
    color: "#9ca3af",
    fontStyle: "italic",
    marginBottom: 12,
    textAlign: "center",
  },
  dayCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#2563eb",
    marginBottom: 10,
  },
  dayHeader: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1e3a8a",
    marginBottom: 8,
  },
  stopRow: {
    flexDirection: "row",
    paddingVertical: 6,
    gap: 10,
  },
  stopTime: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: "600",
    width: 50,
  },
  stopName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  stopTip: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 2,
  },
});
